### ISSUE TITLE
Multiplatform Project: iOS and Android Tutorial:  "Why SharedCode/build/bin folder are not generated". 

### ISSUE THREAD

**Issue by danilodan1485** [JetBrains/kotlin-examples#102]
Good afternoon

When I get to this part of the tutorial I can not  proced because don get SharedCode / build / bin folder. Why this folder is not generated? I did all the steps and I test the android part and is ok.

**Comment by zierka** [comment]
> Let's switch back to the Android Studio and execute the build target of the SharedCode project from the Gradle tool window. The task looks for environment variables set by the Xcode build and copies the right variant of the framework into the SharedCode/build/xcode-frameworks folder. We then include the framework from that folder into the build.

This step should generate those folders. Did this finish successfully?

**Comment by elvinakhundzada** [comment]
Hi, @zierka. I have the same issue. I've cloned and run the app, everything is fine, but I don't have the frameworks generated. Is it compulsory to have a MacOS ?  

I'm using: 

**Windows 10**
**Android Studio 3.3**
**Kotlin version: 1.3.0-rc-190**

**Comment by zierka** [comment]
@elvinakhundzada you need Xcode which runs on Mac only. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by elvinakhundzada** [comment]
Thanks for your answer, @zierka.

You mean, in order to have the frameworks generated, I need to have the Android project & Shared module on a Mac ?

**Comment by danilodan1485** [comment]
@elvinakhundzada Yes,  Is basically this. By the way  @zierka, I solved my problem it was caused cause the xcode version.

I runned "sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/`" for fix the xcode paths. When I updated xcode version, the path wasn't  the same as before.

**Comment by elvinakhundzada** [comment]
Ohh, got it !

Thank you @danilodan1485 !

**Comment by danilodan1485** [comment]
Solved
I runned "sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/`" for fix the xcode paths. When I updated xcode version, the path wasn't the same as before.

**Comment by Harishy** [comment]
If i use above command also, i am unable to generate XCode framework.
