### ISSUE TITLE
Jar build for Gradle Hello World project can not be run

### ISSUE THREAD

**Issue by agap** [JetBrains/kotlin-examples#18]
I've imported the Gradle's hello-world project in Intellij Idea 15. Whenever I run the jar command from the 'Gradle Projects' command, the resulting jar does not have the 'Main-Class' entry in the manifest, so when I try to run "java -jar hello-world.jar", I see the following error: `no main manifest attribute, in build/libs/hello-world.jar`.

**Comment by politedog** [comment]
Adding the following to the end of the build.gradle will allow you to run it with that command line:
`jar {
    manifest {
        attributes 'Main-Class': 'demo.HelloWorldKt'
    }
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}`

**Comment by artemyarulin** [comment]
The issue still exists after 3 years, not a very nice first experience from official hello world example. Workaround works though, wonder why wasn't that merged already?

**Comment by artemyarulin** [comment]
It should work though. I've just made a `git clone` of this repo, then went to `gradle/hello-world` directory and added those lines to `build.gradle`:

```groovy
jar {
    manifest { attributes "Main-Class": mainClassName }
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
}

```
Then compile and run it:

```bash
$ gradle jar
$ java -jar build/libs/hello-world.jar
Hello, world!
```

**Comment by thosakwe** [comment]
Not 100% sure why it didn't work for me; I probably just don't understand Gradle/Groovy yet.

I ended up just using `apply: 'application'`, and then pointing to my `ApplicationKt` class and it all worked fine
