### ISSUE TITLE
android-dagger example problem

### ISSUE THREAD

**Issue by designerMichael** [JetBrains/kotlin-examples#42]
hello, i have met a problem when the androidStudio use the plugin 1.1.2-4 ,my studio version is 2.3.2, when compile the sample which use the "kapt",it would show me an error ：
 Error:Circular dependency between the following tasks:
:app:compileDebugKotlin
\--- :app:kaptDebugKotlin
     \--- :app:compileDebugKotlin (*)
(*) - details omitted (listed previously)

my build.gradle is ：
  ext.kotlin_version = '1.1.2-4'

**Comment by 4u7** [comment]
It is a known bug https://youtrack.jetbrains.com/issue/KT-17936

**Comment by designerMichael** [comment]
thank you! the problem is resolved by changing the ext.kotlin_version = '1.1.2'
