### ISSUE TITLE
Please provide a maven build example for javascript libraries

### ISSUE THREAD

**Issue by nickhristov** [JetBrains/kotlin-examples#52]
Please provide an example which builds and packages a re-usable kotlin to javascript library with Maven (i.e. a library which can be referenced by an unrelated project).

I have build a project which seems to get in this direction somewhat (https://github.com/nickhristov/krakdown), but I was not able to achieve this with another project which used "external" as a keyword (in order to wrap an existing javascript library).

**Comment by nickhristov** [comment]
The issue which I am facing seems to boil down to the following statement from the documentation:

>  Unlike the JVM target, the JS one permits to use external modifier with classes and properties. For example, here's how you can declare the DOM Node class


Hence, a straightforward compilation of the project leads to the following:
```
[ERROR] /run/media/nhh/Development/snapsvg-kotlin/src/main/kotlin/org/github/snapsvg/Snap.kt:[5,15] Unresolved reference: js
[ERROR] /run/media/nhh/Development/snapsvg-kotlin/src/main/kotlin/org/github/snapsvg/Snap.kt:[7,1] Modifier 'external' is not applicable to 'class'
```
With the first several lines of Snap.kt being:

```kotlin
package org.github.snapsvg

import org.w3c.dom.Element
import org.w3c.dom.Node
import kotlin.js.Json

external class SnapElement {
    fun attr (name:String) : Any
    fun attr (json: Json) : Unit
    fun getBBox() : SnapBoundingBox
}
```

Clearly, maven attempts to compile the project as a JVM-bytecode Kotlin vs JS Kotlin. The problem is that even if the maven plugin is configured like this:

```xml
<artifactId>kotlin-maven-plugin</artifactId>
<groupId>org.jetbrains.kotlin</groupId>
<version>${kotlin.version}</version>

<executions>
    <execution>
        <id>compile</id>
        <goals>
           <!-- <goal>compile</goal> -->
            <goal>js</goal>
        </goals>
    </execution>

    <execution>
        <id>test-compile</id>
        <goals>
            <goal>test-compile</goal>
        </goals>
    </execution>

    <execution>
        <id>js</id>
        <goals>
            <goal>js</goal>
        </goals>
    </execution>
</executions>
```
Notice that the `compile` goal here is commented out.

The build succeeds, but it has no source because of dead code stripping (this is a library wrapper after all), so the produced `.js` file is unusable.

Any suggestions on a workable scenario? It seems that the second approach is more likely to succeed, if it could not strip the library code from the `.js` file.

**Comment by konsoletyper** [comment]
> Clearly, maven attempts to compile the project as a JVM-bytecode Kotlin vs JS Kotlin. The problem is that even if the maven plugin is configured like this:

The proper name for test execution is `test-js`, not `test-compile`, as shown by [documentation](http://kotlinlang.org/docs/reference/using-maven.html#targeting-javascript).

> The build succeeds, but it has no source because of dead code stripping (this is a library wrapper after all), so the produced `.js` file is unusable.

By default, compiler *does not* apply dead code elimination. What makes this `.js` file unusable? Did you try to set `metaInfo` property to `true`?

**Comment by nickhristov** [comment]
> By default, compiler does not apply dead code elimination. What makes this .js file unusable? Did you try to set metaInfo property to true?

The produced `.js` file is basically empty.

**Comment by nickhristov** [comment]
Ok, my mistake. 

I just tried a simple exercise of adding a simple `object Foo` to my codebase and it appears in the output javascript file, and in further packaging.

My confusion was a result of the fact that the entire project contained only external declarations, resulting in a pretty much empty `.js` file, while these declarations were getting added to other metadata files which would probably be used for object/method binding.

This issue can be closed.
