### ISSUE TITLE
gradle/hello-world

### ISSUE THREAD

**Issue by jmfayard** [JetBrains/kotlin-examples#6]
Hello, 
I have been testing those examples in IntelliJ 14 and the experience has been quite frustrating
Let's start with the simplest example.
It may be stupid, but I have no idea how to run helloWorld.kt
There is no associated task in 
`$ ./gradlew tasks`

I can only run `$ ./gradlew test` which, if I change `src/test/kotlin/tests.kt` gives me an error

Please add a task `$ ./gradlew greet` for the non gradle pros among us :)

**Comment by NataliaUkhorskaya** [comment]
Fixed in dc55e93e5e1daeaf0f86311e7431843d54a22574

**Comment by XCarbone** [comment]
Is is fixed ? i still don't understand how do we run ...
Plus there is no doc in the project, i don't understand how do you run dokka ?
