### ISSUE TITLE
kotlin-dagger has issue with latest stable Intellij Idea

### ISSUE THREAD

**Issue by atonamy** [JetBrains/kotlin-examples#65]
Please have a look this [video]( https://vimeo.com/244213246) it demonstrates problem very clearly. 
Dagger2 is not generating code with kapt in Intellij Idea, but from gradle wrapper in console work without 
 any issue.

JetBrains please fix this, very troublesome to use Dagger2 with Kotlin in your IDE :(

**Comment by yanex** [comment]
Kapt does not work with JPS (IDEA build system), https://youtrack.jetbrains.com/issue/KT-15040.
Please delegate your build actions to Gradle (Preferences -> Build -> Build Tools -> Gradle -> Runner -> Delegate IDE build/run actions to gradle).
