### ISSUE TITLE
DCE keep package tree

### ISSUE THREAD

**Issue by mtalexo** [JetBrains/kotlin-examples#66]
Is there any way to specify a prefix/wildcard/pattern for runDceKotlinJs.keep to be able to keep an entire package tree?

**Comment by konsoletyper** [comment]
Try to specify package name instead of full function/property name.

**Comment by mtalexo** [comment]
It worked, thanks for the quick reply!
I tried this earlier and thought that the package prefix wasn't getting picked up, but turns out I just wasn't specifying the module name correctly.
