### ISSUE TITLE
How to debug kotlin code in java library

### ISSUE THREAD

**Issue by SJX516** [JetBrains/kotlin-examples#68]
I hava a module similar with "gradle/hello-world" in Android Project(Using Android Studio), and I can run this module use gradle task like ":module:run". however, I found I cannot debug the kotlin code, the normal debug entrance for java is report a error "cannot find or load the main class xx.xxKt", anybody help?

**Comment by yole** [comment]
Please post your question on StackOverflow or on the [Kotlin forums](https://discuss.kotlinlang.org/).
