### ISSUE TITLE
Spring-boot-restful Main-Class

### ISSUE THREAD

**Issue by s1ac2x1** [JetBrains/kotlin-examples#70]
The `gradle bootRun` command does not work without specifying Main-Class property in build

**Comment by jeserkin** [comment]
I say all in all example for spring-boot doesn't work at all

**Comment by caumond** [comment]
I have the same issue. The standard example "spring-boot-restful" does not work with up to date kotlin version (1.2.41). 

I need to add
`
    springBoot
    {
        mainClass = 'org.jetbrains.kotlin.demo.Application'
    }
`
in the build.gradle file

**Comment by yole** [comment]
The example is now updated to Spring Boot 2.1.0, and the `gradle bootRun` command works correctly; there is no need to specify any additional configuration.
